// Unused "using" auto-generated statements:
/*
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
*/


namespace DependencyInjectionDemo.Part1
{
    //internal class Guitar => was generated by Visual Studio

    // Dependency #1: The "Guitar"
    // ***************************
    // Represents one of the dependencies required by the Musician.
    public class Guitar
    {
        // Simulates playing the guitar:
        public void Play()
        {
            Console.WriteLine("Playing Guitar");
        }
    } // Guitar
} // namespace
